project:
  type: website
  output-dir: docs
  render:
    - final_project.qmd
    # - warmup_story.qmd

website:
  title: "SocViz 2023"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - href: final_project.qmd
        text: "Final Project"
      # - href: warmup_story.qmd
      #   text: "Warmup Story"
    right:
      - icon: github
        href: https://github.com/Starostka/socviz
        aria-label: GitHub

format:
  html:
    toc: true
    embed-resources: false
    html-math-method: katex
    # mainfont: "Inter V" # NotoSerif, Inter
    # monofont: "Cascadia Mono"
    theme: #journal flatly, darkly, sandstone
      light: flatly
      dark: darkly
    code-fold: true
    code-summary: "Show the code"
    code-line-numbers: false
    code-copy: true
    code-overflow: wrap
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: github
    number-sections: true
    smooth-scroll: true
    comments:
      hypothesis: 
        theme: clean
      giscus: 
        repo: starostka/socviz
    css: resources/css/custom.css
  ipynb: default


title-block-banner: true
subtitle: "A work in progress"
date: today
author:
  - name: Xinyi Liu
    email: s212620@dtu.dk
  - name: Benjamin Starostka
    email: s184198@dtu.dk

execute:
  freeze: auto
  # cache: true

# metadata
keywords: []
license: CC
pagetitle: ""
subject: ""
title-meta: "Draft document"
author-meta: "Benjamin Starostka Jakobsen"
date-meta: ""
description-meta: ""