project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - pages/melbourne_details.qmd
    - pages/melbourne.qmd
    - pages/melbourne_population.qmd
    - pages/melbourne_residential.qmd
    - pages/melbourne_job.qmd
    - pages/conclusion.qmd
    - pages/san_francisco.qmd
    - about.qmd
    - contact.qmd

website:
  reader-mode: false
  title: "SocViz"
  site-url: "https://starostka.github.io/socviz"
  search: 
    location: navbar
    type: overlay
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: contact.qmd
        text: "Contact"
      - href: pages/san_francisco.qmd
        text: "SF Data Visualization"
    tools:
      - icon: twitter
        href: https://twitter.com/StarostkaB
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/Starostka/socviz
          - text: Report a bug
            url: https://github.com/Starostka/socviz/issues
            # aria-label: GitHub
  sidebar:
    style: "floating"
    contents:
      - section: "Melbourne Pulse"
        contents:
          - pages/melbourne.qmd
          - pages/melbourne_population.qmd
          - pages/melbourne_residential.qmd
          - pages/melbourne_job.qmd
          - pages/conclusion.qmd
          
  repo-url: https://github.com/Starostka/socviz
  repo-actions: [edit, issue]
  page-footer:
    left: "Copyright 2023, Benjamin Starostka & Xinyi Liu"

format:
  html:
    toc: true
    embed-resources: false
    html-math-method: katex
    # mainfont: "Inter V" # NotoSerif, Inter
    # monofont: "Cascadia Mono"
    theme:
      light: [lux, custom-light.scss]
      dark: [lux, custom-dark.scss]
    code-fold: true
    code-summary: "Show the code"
    code-line-numbers: false
    code-copy: true
    code-overflow: wrap
    code-block-bg: true
    # code-block-border-left: "#31BAE9"
    highlight-style: github
    number-sections: true
    # smooth-scroll: true
    comments:
      hypothesis: 
        theme: clean
      giscus: 
        repo: starostka/socviz
  ipynb: default


title-block-banner: false
subtitle: "A work in progress"
date: today
author:
  - name: Xinyi Liu
    email: s212620@dtu.dk
  - name: Benjamin Starostka
    email: s184198@dtu.dk

execute:
  freeze: auto
  # cache: true

# metadata
keywords: [dataviz, visualization, analysis, python, forecast, crime]
license: CC
pagetitle: ""
subject: ""
title-meta: "SocViz Project @ DTU"
author-meta: "Benjamin Starostka Jakobsen"
date-meta: ""
description-meta: ""