---
title: "Introduction"
subtitle: "Final project | Melbourne City Data | Forecasting"
execute:
    freeze: true
title-block-banner: ../assets/dmitry-osipenko-melbourne-unsplash.jpg
---

```{python}
import polars as pl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotx

plt.style.use(matplotx.styles.dufte)
```

# About Melbourne
Melbourne holds the distinction of being the second most populous city in both Australia and Oceania. As the center of south Australia, Melbourne is a sprawling urban area spanning 9,992 km2, which encompasses a metropolitan region comprising 31 municipalities ([Source: Wikipedia](https://www.wikipedia.org/)). It has a population of 5 million, which takes up 19% of the population of Australia.


# Data Sets Details

> The data used is available at [City of Melbourne open data portal](https://data.melbourne.vic.gov.au/explore/?sort=modified&q=forecast)

Here's a brief statistics for each of the datasets used for this project.

1. [City of Melbourne Jobs Forecasts by Small Area 2021-2041](https://data.melbourne.vic.gov.au/explore/dataset/city-of-melbourne-jobs-forecasts-by-small-area-2020-2040/information/)
    * 585 KB, 9114 rows, 5 cols, geodata: area name, age and gender
3. [City of Melbourne Population Forecasts by Small Area 2021-2041](https://data.melbourne.vic.gov.au/explore/dataset/city-of-melbourne-population-forecasts-by-small-area-2020-2040/information/)
    * 710 KB, 17052 rows, 5 cols, geodata: area name
5. [City of Melbourne Dwellings and Household Forecasts by Small Area 2021-2041](https://data.melbourne.vic.gov.au/explore/dataset/city-of-melbourne-dwellings-and-household-forecasts-by-small-area-2020-2040/information/)
    * 161 KB, 2646 rows, 5 cols, geodata: area name
7. [City of Melbourne Floor Space Forecasts by Small Area 2021-2041](https://data.melbourne.vic.gov.au/explore/dataset/city-of-melbourne-floor-space-forecasts-by-small-area-2020-2040/information/)
    * 834 KB, 9996 rows, 5 cols, geodata: area name
9. [Development Activity Monitor](https://data.melbourne.vic.gov.au/explore/dataset/development-activity-monitor/information/)
    * 328 KB, 1430 rows, 42 cols, geodata: yes

<!-- What is your dataset?
Why did you choose this/these particular dataset(s)?
What was your goal for the end user's experience? -->

# The "Pitch" Visualization

During our exploratory data analysis, we made a preliminary examination of the datasets. The sketchy visualization pointed out the central of the most developed area in Melbourne: 
```{python}
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

image1 = mpimg.imread('../assets/pitch1.jpg')
image2 = mpimg.imread('../assets/pitch2.png')

fig, axes = plt.subplots(1, 2)
plt.suptitle('The "Pitch" Visualization', y=0.71)

axes[0].imshow(image1)
axes[0].axis('off')

axes[1].imshow(image2)
axes[1].axis('off')


plt.tight_layout()

plt.show()

```
The exploratory data analysis enabled us to delve deeper into the data and uncover valuable insights. 
